name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_SHA_NAME: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml -P prod
    - uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'wow-checklist-backend'
        TAG: 'dev'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: garygrossgarten/github-action-ssh@release
      with:
        command: docker pull ${{ needs.build.outputs.IMAGE_SHA_NAME }} &&
          docker stop wow-checklist-backend &&
          docker run --rm --name wow-checklist-backend -p 8090:8080 -d --env-file ${{ secrets.DEV_ENV_FILE }} ${{ needs.build.outputs.IMAGE_SHA_NAME }}
        host: ${{ secrets.DEV_HOST }}
        port: ${{ secrets.DEV_PORT }}
        username: ${{ secrets.DEV_USER }}
        passphrase: ${{ secrets.DEV_SSHPASS }}
        privateKey: ${{ secrets.DEV_SSHKEY }}
